### ISSUE TITLE
'타임라인에서 사용되는 게시글' 컴포넌트 작성

### ISSUE THREAD

**Issue by codenamenam** [SWM-mini-47/SWMinder-front#3]
### TO DO
- 컴포넌트 디자인
### Description
- 세부 정보(선택)

**Comment by junhea** [comment]
main에 이슈 템플릿과 lint 설정 파일을 추가하여
rebase 하고 진행하셔야 할 것 같습니다

**Comment by codenamenam** [comment]
아하 넵! 다시 확인해보겠습니다
